name: Build Executables

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
      shell: bash
      if: runner.os != 'Windows'

    - name: Install dependencies on Windows
      run: |
        python -m pip install --upgrade pip
        if exist requirements.txt pip install -r requirements.txt
      shell: cmd
      if: runner.os == 'Windows'

    - name: Build executable
      run: |
        pyinstaller --onefile dialog.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/
