# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

permissions: write-all

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pytest
    - name: pyinstaller
      run: |
        pyinstaller --name dialog-${{ matrix.os }} -F dialog.py
        mv dist dist-${{ matrix.os }}/dist
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dialog
    #     path: dist/

    - name: Configure Git
      run: |
        git config --global user.name 'li1055107552'
        git config --global user.email 'li1055107552@163.com'
      
    - name: Sync dist to GitHub
      run: |
        git add dist-*
        git checkout -b dist-update
        git commit -m "Update dist"
        git push -u origin HEAD:dist-update --force
        # git push -u origin HEAD:dist-update

